import type { IconType } from "react-icons";
import {
  SiReact,
  SiSvelte,
  SiNextdotjs,
  SiAstro,
  SiAngular,
  SiTypescript,
  SiJavascript,
  SiNodedotjs,
  SiNestjs,
  SiPython,
  SiTailwindcss,
  SiBootstrap,
  SiMui,
  SiIonic,
  SiMysql,
  SiPostgresql,
  SiMongodb,
  SiRedis,
  SiSqlite,
  SiDocker,
  SiGooglecloud,
  SiGit,
  SiGithub,
  SiGraphql,
  SiFlask,
  SiClaude,
  SiOpenai,
  SiNpm,
} from "react-icons/si";
import { FaAws } from "react-icons/fa6";

export type Tech = { name: string; Icon: IconType };

// Only verified icons — drives the marquee and any icon grid.
export const techMarquee: Tech[] = [
  { name: "TypeScript", Icon: SiTypescript },
  { name: "Svelte", Icon: SiSvelte },
  { name: "React", Icon: SiReact },
  { name: "Next.js", Icon: SiNextdotjs },
  { name: "Astro", Icon: SiAstro },
  { name: "Node.js", Icon: SiNodedotjs },
  { name: "NestJS", Icon: SiNestjs },
  { name: "Claude", Icon: SiClaude },
  { name: "OpenAI", Icon: SiOpenai },
  { name: "Angular", Icon: SiAngular },
  { name: "Python", Icon: SiPython },
  { name: "Flask", Icon: SiFlask },
  { name: "GraphQL", Icon: SiGraphql },
  { name: "Tailwind", Icon: SiTailwindcss },
  { name: "Ionic", Icon: SiIonic },
  { name: "Material UI", Icon: SiMui },
  { name: "Bootstrap", Icon: SiBootstrap },
  { name: "PostgreSQL", Icon: SiPostgresql },
  { name: "MySQL", Icon: SiMysql },
  { name: "MongoDB", Icon: SiMongodb },
  { name: "Redis", Icon: SiRedis },
  { name: "SQLite", Icon: SiSqlite },
  { name: "Docker", Icon: SiDocker },
  { name: "AWS", Icon: FaAws },
  { name: "Google Cloud", Icon: SiGooglecloud },
  { name: "JavaScript", Icon: SiJavascript },
  { name: "Git", Icon: SiGit },
  { name: "GitHub", Icon: SiGithub },
  { name: "npm", Icon: SiNpm },
];
